version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: python run.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  celery-worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A celery_worker.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web